### ISSUE TITLE
libQtJambi.so.5.15.5' was not found in 'java.library.path

### ISSUE THREAD

**Issue by GlassGhost** [GlassGhost/NoSpringBoot#1]
owner@localhost:~$ git clone https://github.com/GlassGhost/NoSpringBoot
    cd ./NoSpringBoot
    ant
    java -jar './EventTest.jar'
    Cloning into 'NoSpringBoot'...
    remote: Enumerating objects: 56, done.
    remote: Counting objects: 100% (56/56), done.
    remote: Compressing objects: 100% (26/26), done.
    remote: Total 56 (delta 22), reused 56 (delta 22), pack-reused 0
    Receiving objects: 100% (56/56), 11.34 KiB | 5.67 MiB/s, done.
    Resolving deltas: 100% (22/22), done.
    Buildfile: /home/owner/NoSpringBoot/build.xml

    compile:
        [mkdir] Created dir: /home/owner/NoSpringBoot/build
        [javac] Compiling 3 source files to /home/owner/NoSpringBoot/build
        [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
        [javac] /home/owner/NoSpringBoot/src/EventTest/Test.java:16: error: package io.qt.widgets does not exist
        [javac] import io.qt.widgets.*;
        [javac] ^
        [javac] /home/owner/NoSpringBoot/src/EventTest/Test.java:28: error: cannot find symbol
        [javac]         QApplication.initialize(args);
        [javac]         ^
        [javac]   symbol:   variable QApplication
        [javac]   location: class Test
        [javac] /home/owner/NoSpringBoot/src/EventTest/Test.java:29: error: cannot find symbol
        [javac]         QMessageBox.information(null, "QtJambi", "Hello World!");
        [javac]         ^
        [javac]   symbol:   variable QMessageBox
        [javac]   location: class Test
        [javac] /home/owner/NoSpringBoot/src/EventTest/Test.java:30: error: cannot find symbol
        [javac]         QApplication.shutdown();
        [javac]         ^
        [javac]   symbol:   variable QApplication
        [javac]   location: class Test
        [javac] 4 errors
        [javac] 1 warning

    BUILD FAILED
    /home/owner/NoSpringBoot/build.xml:48: Compile failed; see the compiler error output for details.

    Total time: 2 seconds
    Error: Unable to access jarfile ./EventTest.jar

after copying the "qtjambi-5.15.5.jar" into the lib dir the error above goes away, but of course we get a new one

    owner@localhost:~/NoSpringBoot$ ant
    Buildfile: /home/owner/NoSpringBoot/build.xml

    compile:
        [javac] Compiling 3 source files to /home/owner/NoSpringBoot/build
        [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
        [javac] 1 warning

    package:
          [jar] Building jar: /home/owner/NoSpringBoot/EventTest.jar

    BUILD SUCCESSFUL
    Total time: 3 seconds
    owner@localhost:~/NoSpringBoot$ java -jar './EventTest.jar'
    Something thrown
    I caught something!!
    Exception in thread "main" io.qt.QLibraryNotFoundError: Library 'libQtJambi.so.5.15.5' was not found in 'java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib'
        at io.qt.internal.NativeLibraryManager.loadLibrary_helper(NativeLibraryManager.java:1449)
        at io.qt.internal.NativeLibraryManager.loadNativeLibrary(NativeLibraryManager.java:1160)
        at io.qt.internal.NativeLibraryManager.loadQtJambiLibrary(NativeLibraryManager.java:931)
        at io.qt.internal.NativeLibraryManager.loadQtJambiLibrary(NativeLibraryManager.java:917)
        at io.qt.internal.QtJambi_LibraryUtilities.<clinit>(QtJambi_LibraryUtilities.java:53)
        at io.qt.internal.QtJambiObject.<clinit>(QtJambiObject.java:39)
        at EventTest.Test.main(Test.java:28)
    owner@localhost:~/NoSpringBoot$

**Comment by omix** [comment]
You need to copy [qtjambi-native-linux-x64-5.15.5.jar](https://search.maven.org/artifact/io.qtjambi/qtjambi-native-linux-x64/5.15.5/jar) to the same directory as qtjambi-5.15.5.jar

**Comment by GlassGhost** [comment]
@omix THANK YOU, that got rid of that error. there is another error but I think it would be appropriate to do that as a separate issue.

**Comment by GlassGhost** [comment]
I added a section on your advice the readme on getting the correct libraries should make the jar able to run on all OS when it's done

https://github.com/GlassGhost/NoSpringBoot/commit/dcb7815f7c2cb2328f3dcf2af6b9a31a675fe46f
